name: postman-newman-dockerhub-azureappservice

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGEM_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/apifinancas-classlib-dotnet5
  NOME_WEBAPP: groffefinancas
  CAMINHO_TESTES: ./Tests
  
jobs:

  build-tests-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build de imagem
      run: docker build . --file Dockerfile --tag ${{ env.IMAGEM_DOCKERHUB }}:latest

    - name: Criação de container para testes com a API
      run: |
        docker run --name api-testes -p 5000:80 -d ${{ env.IMAGEM_DOCKERHUB }}:latest
        docker container ls

    - name: Testes da API REST com Newman
      run: |
        cd ${{ env.CAMINHO_TESTES }}
        echo "** Versão Global do Newman **"
        newman -v
        newman run CalculoJurosCompostos.postman_collection.json -d data-tests.json
        
    - name: Login no Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        docker tag ${{ env.IMAGEM_DOCKERHUB }}:latest ${{ env.IMAGEM_DOCKERHUB }}:$GITHUB_RUN_NUMBER
        docker push --all-tags ${{ env.IMAGEM_DOCKERHUB }}

  deployment-azwebapp:
    needs: [build-tests-push]
    
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login - Conectando com Credenciais no Azure
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp - Deployment da Aplicacao
      uses: Azure/webapps-deploy@v2.2.3
      with:
        app-name: ${{ env.NOME_WEBAPP }}
        images: '${{ env.IMAGEM_DOCKERHUB }}:${{ github.run_number }}'
